name: AR PR Deployment

on:
    pull_request:
        types: [labeled]
        paths-ignore:
            - "dotcom-rendering/**"

jobs:
    pr_deployment:
        name: AR PR deployment
        # We only want to run the app if the PR Deployment label has been added
        if: ${{ github.event.label.id == 2500798832 }}

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2.3.4
            - uses: guardian/actions-setup-node@main

            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: node-
            - name: install
              run: npm ci
              working-directory: apps-rendering
            - name: run
              working-directory: apps-rendering
              run: |
                  npm install -g ngrok
                  npm run watch & 
                  timeout 1h ngrok http 8080 -log=stdout -host-header=rewrite | \
                    grep --line-buffered -o 'https://.*' | \
                    xargs -L1 -I{} -t \
                      curl -X POST -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} -d "{\"state\":\"success\", \"target_url\":\"{}\", \"context\":\"PR deployment\", \"description\":\"This PR is now live until `date -d "+1 hour" "+%a %H:%M"`. Click details to access it ->\"}"
              env:
                  APIS_IMG_SALT: ${{ secrets.APIS_IMG_SALT }}
                  CAPI_KEY: ${{ secrets.CAPI_KEY }}
                  TZ: "/usr/share/zoneinfo/Europe/London"
