name: DCR Build Check
on:
    push:
        paths-ignore:
            - "apps-rendering/**"

jobs:
    build_check:
        name: DCR Build Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2.3.4

            - name: Install Node
              uses: guardian/actions-setup-node@main

            # Cache npm dependencies using https://github.com/bahmutov/npm-install
            - uses: bahmutov/npm-install@v1
              with:
                  working-directory: dotcom-rendering

            - name: Install
              run: yarn
              working-directory: dotcom-rendering

            - name: Generate production build
              run: make build
              working-directory: dotcom-rendering

            - name: Validate Build
              run: make buildCheck
              working-directory: dotcom-rendering
