# This action runs every day at 6 AM and on every push
# If the branch it's running on is main then it will run snyk monitor (reports vulnerabilities to snyk.io)
# Otherwise it will run snyk test
name: DCR Snyk

on:
    schedule:
        - cron: '0 6 * * *'
    push:
        paths-ignore:
            - "apps-rendering/**"
    workflow_dispatch:

jobs:
    security:
        name: DCR Snyk
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2.3.4

            - name: Set command to monitor
              if: github.ref == 'refs/heads/main'
              run: echo "SNYK_COMMAND=monitor" >> $GITHUB_ENV

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@0.3.0
              continue-on-error: true # To make sure that SARIF upload gets called
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  args: --org=the-guardian --project-name=${{ github.repository }} --file=dotcom-rendering/yarn.lock --dev=true --prune-repeated-subdependencies --sarif-file-output=snyk-node.sarif
                  command: test

            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v1
              with:
                  sarif_file: snyk-node.sarif
                  checkout_path: ${{ github.workspace }}/dotcom-rendering

            - name: Run Snyk monitor to update snyk.io
              if: github.ref == 'refs/heads/main'
              uses: snyk/actions/node@0.3.0
              continue-on-error: true # To make sure that SARIF upload gets called
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  args: --org=the-guardian --project-name=${{ github.repository }} --file=dotcom-rendering/yarn.lock --dev=true --prune-repeated-subdependencies
                  command: monitor
